### ISSUE TITLE
ComponentsByStructureResolver is broken

### ISSUE THREAD

**Issue by synth** [BindaCMS/binda-api#18]
### Issue
When querying for components by structure, the server returns 500 error. 

### Expected behavior
The server returns proper payload.

### How to reproduce the issue
Sample request:
```
{ components_by_structure(structure_slug:"announcement"){ edges { node {  id, name} } }}
```

Binda API version:
v0.2.0.alpha.2 - but looks like broken since 2a0c51ccfecff2ece2644fc181514f88aa734a36

Binda version:0.1.11
Rails version: 5.1.1

### Additional:
This looks like it was never tested or used since authorization was implemented as its clear from looking at the code that it would never work. Attributes are simply not defined such as `user`, and `structure_slug`.

**Comment by synth** [comment]
We're making a bet on Binda and Binda-Api :) So, we'll be making PR's and contributing as we find issues :)
Would love to see this get out of Alpha.

**Comment by a-barbieri** [comment]
> We're making a bet on Binda and Binda-Api :)

Thank you @synth. Help is much needed! 🥇 

> This looks like it was never tested or used since authorization was implemented as its clear from looking at the code that it would never work

It's totally possible as it was more of an experiment than an actual plugin at the beginning. 

Happy that you fixed it. I'll merge it now.

Do you need me to cut a new version?

**Comment by synth** [comment]
@a-barbieri Sure, let's bump the alpha a notch :)

**Comment by a-barbieri** [comment]
New alpha ready. --> https://github.com/BindaCMS/binda-api/releases/tag/v0.2.0.alpha.3
